repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0 # Modify this to be the version you want
    hooks:
      - id: pydocstyle

  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.2
    hooks:
      - id: pip-audit
        name: pip-audit
        entry: pip-audit
        args: []
        language: system
        pass_filenames: false
        types: [python] # Opcional: se você quiser que isso seja executado apenas quando arquivos Python forem alterados.
ci:
  # Leave pip-audit to only run locally and not in CI
  # pre-commit.ci does not allow network calls
  skip: [pip-audit]
